---
- name: Run whoami
  shell: whoami
  register: whoamiVar

- name: Print whoamiVar
  debug:
    msg: "{{ whoamiVar }}"
    
- name: Download Node.js package
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present
